/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.radiocheck;

import javax.swing.JOptionPane;

/**
 *
 * @author D-12
 */
public class RadioCheckF extends javax.swing.JFrame {
    

    /**
     * Creates new form RadioCheckF
     */
    
    String nama, gender, alamat, pendidikan, nim, hbOlahraga, hbGaming, hbTravelling, hbTech, hbMembaca, hbMakan;
    public RadioCheckF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        txtbiodata = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        txtKelamin = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        txtNIM = new javax.swing.JLabel();
        tfNIM = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        txtJenjang = new javax.swing.JLabel();
        cmbJenjang = new javax.swing.JComboBox<>();
        txtHobby = new javax.swing.JLabel();
        boxOlahraga = new javax.swing.JCheckBox();
        boxGaming = new javax.swing.JCheckBox();
        boxTravelling = new javax.swing.JCheckBox();
        boxMembaca = new javax.swing.JCheckBox();
        boxTech = new javax.swing.JCheckBox();
        boxMakan = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtbiodata.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        txtbiodata.setText("BioData");

        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNama.setText("Nama");

        txtKelamin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKelamin.setText("Jenis Kelamin");

        bgGender.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbLaki.setText("Laki-Laki");

        bgGender.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");

        txtNIM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNIM.setText("NIM");

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlamat.setText("Alamat");

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        txtJenjang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtJenjang.setText("Jenjang Pendidikan");

        cmbJenjang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "TK", "SD", "SMP", "SMA", "S1", "S2", "S3" }));

        txtHobby.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHobby.setText("Hobby");

        boxOlahraga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxOlahraga.setText("Olahraga");

        boxGaming.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxGaming.setText("Gaming");

        boxTravelling.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxTravelling.setText("Travelling");

        boxMembaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxMembaca.setText("Membaca");
        boxMembaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMembacaActionPerformed(evt);
            }
        });

        boxTech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxTech.setText("Technology");

        boxMakan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxMakan.setText("Makan");
        boxMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMakanActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 255, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit!");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 153, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 51, 51));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNama)
                                .addComponent(txtNIM))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(tfNama)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtAlamat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtKelamin)
                            .addGap(18, 18, 18)
                            .addComponent(rbLaki)
                            .addGap(18, 18, 18)
                            .addComponent(rbPerempuan))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtJenjang)
                            .addGap(18, 18, 18)
                            .addComponent(cmbJenjang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHobby)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTravelling)
                            .addComponent(boxOlahraga)
                            .addComponent(boxTech))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxMakan)
                            .addComponent(boxGaming)
                            .addComponent(boxMembaca))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtbiodata)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbiodata)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIM)
                    .addComponent(tfNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelamin)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJenjang)
                    .addComponent(cmbJenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHobby)
                    .addComponent(boxOlahraga)
                    .addComponent(boxGaming))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTravelling)
                    .addComponent(boxMembaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTech)
                    .addComponent(boxMakan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMakanActionPerformed

    private void boxMembacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMembacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMembacaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        nama = tfNama.getText();
        nim = tfNIM.getText();
        alamat = taAlamat.getText();
        
        pendidikan = cmbJenjang.getSelectedItem().toString();
        
        if (rbLaki.isSelected()){
            gender = "Laki-Laki";
        } else{
            gender = "perempuan";
        }
        
        if(boxOlahraga.isSelected()){
            hbOlahraga = "Olahraga";
        }else{
            hbOlahraga = "";
        }
        
        if(boxGaming.isSelected()){
            hbGaming = "Gaming";
        }else{
            hbGaming = "";
        }
        
        if(boxTravelling.isSelected()){
            hbTravelling = "Travelling";
        }else{
            hbTravelling = "";
        }
        
        if(boxMembaca.isSelected()){
            hbMembaca = "Membaca";
        }else{
            hbMembaca = "";
        }
        
        if(boxTech.isSelected()){
            hbTech = "Technology";
        }else{
            hbTech = "";
        }
        
        if(boxMakan.isSelected()){
            hbMakan = "Mukbang";
        }else{
            hbMakan = "";
        }
        
        JOptionPane.showMessageDialog(this, "Nama : "+nama+"\nNIM : "+nim+"\nGender : "+gender+"\nAlamat : "+alamat+"\nJenjang Pendidikan : "+pendidikan+"\nHobi : "+hbOlahraga+"\n"+hbGaming+"\n"+hbTravelling+"\n"+hbMembaca+"\n"+hbTech+"\n"+hbMakan,"BioData", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        tfNama.setText("");
        tfNIM.setText("");
        taAlamat.setText("");
        bgGender.clearSelection();
        boxOlahraga.setSelected(false);
        boxGaming.setSelected(false);
        boxTravelling.setSelected(false);
        boxMembaca.setSelected(false);
        boxTech.setSelected(false);
        boxMakan.setSelected(false);
        cmbJenjang.setSelectedItem(null);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioCheckF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioCheckF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioCheckF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioCheckF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioCheckF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JCheckBox boxGaming;
    private javax.swing.JCheckBox boxMakan;
    private javax.swing.JCheckBox boxMembaca;
    private javax.swing.JCheckBox boxOlahraga;
    private javax.swing.JCheckBox boxTech;
    private javax.swing.JCheckBox boxTravelling;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbJenjang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfNIM;
    private javax.swing.JTextField tfNama;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtHobby;
    private javax.swing.JLabel txtJenjang;
    private javax.swing.JLabel txtKelamin;
    private javax.swing.JLabel txtNIM;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtbiodata;
    // End of variables declaration//GEN-END:variables
}
